export * from "./Depto";
export * from "./Distrito";
export * from "./Municipio";
export * from "./Page"; 
export * from "./Usuario";
export * from "./Parroquia";
export * from "./Ministro";
export * from "./Confirmacion";
export * from "./Logo";
