services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./data:/data/db

  backend:
    build: .
    container_name: iglesia-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongodb